package diomaxius.whattocookwith

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import dagger.hilt.android.AndroidEntryPoint
import diomaxius.whattocookwith.navigation.AppNavigation
import diomaxius.whattocookwith.ui.theme.WhatToCookWithTheme
/*
I'd say this is the alpha stage of a working MVP project.
So please don't judge me harshly, as this is not a production ready app.
All the development time was spent creating the business logic and connecting it to the UI.
So, my app doesn't have many animations or screen transitions, as
the business logic was quite complex.

I also recorded a video demonstration of my app. While recording the video,
I discovered a bug, but I didn't demonstrate it in the video.
I described this bug in the data layer.

I see great potential in this app and will continue to work on it.
I also like the idea of the app itself.
I might switch to packages per feature instead of a monolith.

The images and recipes for the app were generated by AI.

Video demonstration:
https://drive.google.com/file/d/1k39gnatK-9jua_i2_mNyFmkvHJYu-9x6/view?usp=sharing
*/
@AndroidEntryPoint
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            WhatToCookWithTheme {
                AppNavigation()
            }
        }
    }
}